questions = {
    "Which language is used for data engineering?" : "Python",
    "Which loop is called as iterative loop?" : "for",
    "What is Python?": "Language",
    "Which keyword defines a function?": "def",
    "How do you create a list?": "list",
    "What is the output of 2 ** 3?": "8",
    "Which data type stores True/False?": "bool",
    "How do you start a comment?": "hash",
    "Mutable collection type?": "list",
    "Immutable collection type?": "tuple",
    "Floor division operator?": "floor",
    "How to import a module?": "import",
    "Which function gives number of items?": "len",
    "Collection of key-value pairs?": "dict",
    "How to handle exceptions?": "try",
    "Equality operator?": "==",
    "Method to add item to list?": "append",
    "Type of 10?": "int",
    "Loop keyword?": "for",
    "String to integer function?": "int",
    "Anonymous function keyword?": "lambda",
    "Keyword to create class?": "class"
}